import {
  SiNextdotjs,
  SiVite,
  SiAxios,
  SiRecoil,
  SiReactquery,
  SiNodedotjs,
  SiNestjs,
  SiExpress,
  SiFastapi,
  SiGraphql,
  SiTypescript,
  SiJavascript,
  SiPython,
  SiPostgresql,
  SiMysql,
  SiSupabase,
  SiPrisma,
  SiMantine,
  SiStyledcomponents,
  SiFramer,
  SiFontawesome,
  SiVercel,
  SiCloudflare,
  SiDocker,
  SiFirebase,
  SiEslint,
  SiPrettier,
  SiNotion,
  SiGithub,
  SiGoogleanalytics,
  SiStorybook,
  SiFigma,
  SiPostman,
  SiGithubcopilot,
  SiReact,
  SiReactHex,
  SiNextdotjsHex,
  SiGithubcopilotHex,
  SiPostmanHex,
  SiFigmaHex,
  SiAxiosHex,
  SiRecoilHex,
  SiReactqueryHex,
  SiNodedotjsHex,
  SiNestjsHex,
  SiExpressHex,
  SiFastapiHex,
  SiGraphqlHex,
  SiTypescriptHex,
  SiPostgresqlHex,
  SiMysqlHex,
  SiSupabaseHex,
  SiPrismaHex,
  SiMantineHex,
  SiStyledcomponentsHex,
  SiFramerHex,
  SiFontawesomeHex,
  SiVercelHex,
  SiCloudflareHex,
  SiDockerHex,
  SiFirebaseHex,
  SiEslintHex,
  SiPrettierHex,
  SiNotionHex,
  SiGithubHex,
  SiGoogleanalyticsHex,
  SiStorybookHex,
  SiGithubactions,
  SiGithubactionsHex,
  SiViteHex,
  SiPythonHex,
} from '@icons-pack/react-simple-icons';
import { memo, ReactNode } from 'react';
import Image from 'next/image';

export enum ETECH_STACK_KIND {
  FRONTEND = 'frontend',
  BACKEND = 'backend',
  LANGUAGE = 'language',
  DATABASE = 'database',
  API = 'api',
  STATE = 'state',
  ORM = 'orm',
  STYLE = 'style',
  INFRA = 'infra',
  CICD = 'CI/CD',
  TOOL = 'tool',
}

const CodeIcon = memo(() => {
  return (
    <Image src="/icons/code.svg" alt="" width={24} height={24} style={{ objectFit: 'contain', filter: 'invert(1)' }} />
  );
});

export enum ETECH_STACK_LIST {
  REACT = 'React',
  REACT_NATIVE = 'React Native',
  NEXT_JS = 'Next.js',
  VITE = 'Vite',
  AXIOS = 'Axios',
  ZUSTAND = 'Zustand',
  RECOIL = 'Recoil',
  TANSTACK_QUERY = 'TanStack Query',
  NODE_JS = 'Node.js',
  NESTJS = 'NestJS',
  EXPRESS = 'Express',
  FASTAPI = 'FastAPI',
  GRAPHQL = 'GraphQL',
  REST_API = 'REST API',
  TYPESCRIPT = 'TypeScript',
  JAVASCRIPT = 'JavaScript',
  PYTHON = 'Python',
  POSTGRESQL = 'PostgreSQL',
  MYSQL = 'MySQL',
  SUPABASE = 'Supabase',
  PRISMA = 'Prisma',
  MANTINE = 'Mantine',
  STYLED_COMPONENTS = 'Styled Components',
  FRAMER_MOTION = 'Framer Motion',
  REANIMATED = 'Reanimated',
  FONT_AWESOME = 'Font Awesome',
  VERCEL = 'Vercel',
  CLOUDFLARE = 'Cloudflare',
  DOCKER = 'Docker',
  AWS = 'AWS',
  ORACLE = 'Oracle',
  FIREBASE = 'Firebase',
  ESLINT = 'ESLint',
  PRETTIER = 'Prettier',
  NOTION = 'Notion',
  GITHUB = 'GitHub',
  OPENAI = 'OpenAI',
  GOOGLE_ANALYTICS = 'Google Analytics',
  STORYBOOK = 'Storybook',
  GITHUB_ACTIONS = 'GitHub Actions',
  FIGMA = 'Figma',
  POSTMAN = 'Postman',
  GITHUB_COPILOT = 'GitHub Copilot',
  TWILIO = 'Twilio',
}

export type ITechStack = {
  name: ETECH_STACK_LIST;
  kind: ETECH_STACK_KIND;
  icon: ReactNode;
  tier: 'MAIN' | 'USED';
};

export const TECH_STACK_CONSTANT: ITechStack[] = [
  {
    name: ETECH_STACK_LIST.REACT,
    kind: ETECH_STACK_KIND.FRONTEND,
    tier: 'MAIN',
    icon: <SiReact size={24} color={SiReactHex} />,
  },
  {
    name: ETECH_STACK_LIST.REACT_NATIVE,
    kind: ETECH_STACK_KIND.FRONTEND,
    tier: 'MAIN',
    icon: <SiReact size={24} color={SiReactHex} />,
  },
  {
    name: ETECH_STACK_LIST.NEXT_JS,
    kind: ETECH_STACK_KIND.FRONTEND,
    tier: 'MAIN',
    icon: <SiNextdotjs size={24} color={SiNextdotjsHex} />,
  },
  {
    name: ETECH_STACK_LIST.VITE,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiVite size={24} color={SiViteHex} />,
  },
  {
    name: ETECH_STACK_LIST.AXIOS,
    kind: ETECH_STACK_KIND.API,
    tier: 'USED',
    icon: <SiAxios size={24} color={SiAxiosHex} />,
  },
  {
    name: ETECH_STACK_LIST.ZUSTAND,
    kind: ETECH_STACK_KIND.STATE,
    tier: 'MAIN',
    icon: <CodeIcon />,
  },
  {
    name: ETECH_STACK_LIST.RECOIL,
    kind: ETECH_STACK_KIND.STATE,
    tier: 'USED',
    icon: <SiRecoil size={24} color={SiRecoilHex} />,
  },
  {
    name: ETECH_STACK_LIST.TANSTACK_QUERY,
    kind: ETECH_STACK_KIND.STATE,
    tier: 'USED',
    icon: <SiReactquery size={24} color={SiReactqueryHex} />,
  },
  {
    name: ETECH_STACK_LIST.NODE_JS,
    kind: ETECH_STACK_KIND.BACKEND,
    tier: 'MAIN',
    icon: <SiNodedotjs size={24} color={SiNodedotjsHex} />,
  },
  {
    name: ETECH_STACK_LIST.NESTJS,
    kind: ETECH_STACK_KIND.BACKEND,
    tier: 'MAIN',
    icon: <SiNestjs size={24} color={SiNestjsHex} />,
  },
  {
    name: ETECH_STACK_LIST.EXPRESS,
    kind: ETECH_STACK_KIND.BACKEND,
    tier: 'MAIN',
    icon: <SiExpress size={24} color={SiExpressHex} />,
  },
  {
    name: ETECH_STACK_LIST.FASTAPI,
    kind: ETECH_STACK_KIND.BACKEND,
    tier: 'USED',
    icon: <SiFastapi size={24} color={SiFastapiHex} />,
  },
  {
    name: ETECH_STACK_LIST.GRAPHQL,
    kind: ETECH_STACK_KIND.API,
    tier: 'MAIN',
    icon: <SiGraphql size={24} color={SiGraphqlHex} />,
  },
  {
    name: ETECH_STACK_LIST.REST_API,
    kind: ETECH_STACK_KIND.API,
    tier: 'MAIN',
    icon: <CodeIcon />,
  },
  {
    name: ETECH_STACK_LIST.TYPESCRIPT,
    kind: ETECH_STACK_KIND.LANGUAGE,
    tier: 'MAIN',
    icon: <SiTypescript size={60} color={SiTypescriptHex} />,
  },
  {
    name: ETECH_STACK_LIST.JAVASCRIPT,
    kind: ETECH_STACK_KIND.LANGUAGE,
    tier: 'MAIN',
    icon: <SiJavascript size={24} color="#F7DF1E" />,
  },
  {
    name: ETECH_STACK_LIST.PYTHON,
    kind: ETECH_STACK_KIND.LANGUAGE,
    tier: 'USED',
    icon: <SiPython size={24} color={SiPythonHex} />,
  },
  {
    name: ETECH_STACK_LIST.POSTGRESQL,
    kind: ETECH_STACK_KIND.DATABASE,
    tier: 'MAIN',
    icon: <SiPostgresql size={24} color={SiPostgresqlHex} />,
  },
  {
    name: ETECH_STACK_LIST.MYSQL,
    kind: ETECH_STACK_KIND.DATABASE,
    tier: 'USED',
    icon: <SiMysql size={24} color={SiMysqlHex} />,
  },
  {
    name: ETECH_STACK_LIST.SUPABASE,
    kind: ETECH_STACK_KIND.BACKEND,
    tier: 'MAIN',
    icon: <SiSupabase size={24} color={SiSupabaseHex} />,
  },
  {
    name: ETECH_STACK_LIST.PRISMA,
    kind: ETECH_STACK_KIND.ORM,
    tier: 'MAIN',
    icon: <SiPrisma size={24} color={SiPrismaHex} />,
  },
  {
    name: ETECH_STACK_LIST.MANTINE,
    kind: ETECH_STACK_KIND.STYLE,
    tier: 'MAIN',
    icon: <SiMantine size={24} color={SiMantineHex} />,
  },
  {
    name: ETECH_STACK_LIST.STYLED_COMPONENTS,
    kind: ETECH_STACK_KIND.STYLE,
    tier: 'MAIN',
    icon: <SiStyledcomponents size={24} color={SiStyledcomponentsHex} />,
  },
  {
    name: ETECH_STACK_LIST.FRAMER_MOTION,
    kind: ETECH_STACK_KIND.STYLE,
    tier: 'MAIN',
    icon: <SiFramer size={24} color={SiFramerHex} />,
  },
  {
    name: ETECH_STACK_LIST.REANIMATED,
    kind: ETECH_STACK_KIND.STYLE,
    tier: 'MAIN',
    icon: <Image src="/icons/reanimated.svg" alt="" width={24} height={24} style={{ objectFit: 'contain' }} />,
  },
  {
    name: ETECH_STACK_LIST.FONT_AWESOME,
    kind: ETECH_STACK_KIND.STYLE,
    tier: 'MAIN',
    icon: <SiFontawesome size={24} color={SiFontawesomeHex} />,
  },
  {
    name: ETECH_STACK_LIST.VERCEL,
    kind: ETECH_STACK_KIND.INFRA,
    tier: 'MAIN',
    icon: <SiVercel size={24} color={SiVercelHex} />,
  },
  {
    name: ETECH_STACK_LIST.CLOUDFLARE,
    kind: ETECH_STACK_KIND.INFRA,
    tier: 'USED',
    icon: <SiCloudflare size={24} color={SiCloudflareHex} />,
  },
  {
    name: ETECH_STACK_LIST.DOCKER,
    kind: ETECH_STACK_KIND.INFRA,
    tier: 'MAIN',
    icon: <SiDocker size={24} color={SiDockerHex} />,
  },
  {
    name: ETECH_STACK_LIST.AWS,
    kind: ETECH_STACK_KIND.INFRA,
    tier: 'USED',
    icon: <CodeIcon />,
  },
  {
    name: ETECH_STACK_LIST.ORACLE,
    kind: ETECH_STACK_KIND.INFRA,
    tier: 'MAIN',
    icon: <CodeIcon />,
  },
  {
    name: ETECH_STACK_LIST.FIREBASE,
    kind: ETECH_STACK_KIND.BACKEND,
    tier: 'MAIN',
    icon: <SiFirebase size={24} color={SiFirebaseHex} />,
  },
  {
    name: ETECH_STACK_LIST.ESLINT,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiEslint size={24} color={SiEslintHex} />,
  },
  {
    name: ETECH_STACK_LIST.PRETTIER,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiPrettier size={24} color={SiPrettierHex} />,
  },
  {
    name: ETECH_STACK_LIST.NOTION,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiNotion size={24} color={SiNotionHex} />,
  },
  {
    name: ETECH_STACK_LIST.GITHUB,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiGithub size={24} color={SiGithubHex} />,
  },
  {
    name: ETECH_STACK_LIST.OPENAI,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <CodeIcon />,
  },
  {
    name: ETECH_STACK_LIST.GOOGLE_ANALYTICS,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'USED',
    icon: <SiGoogleanalytics size={24} color={SiGoogleanalyticsHex} />,
  },
  {
    name: ETECH_STACK_LIST.STORYBOOK,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'USED',
    icon: <SiStorybook size={24} color={SiStorybookHex} />,
  },
  {
    name: ETECH_STACK_LIST.GITHUB_ACTIONS,
    kind: ETECH_STACK_KIND.CICD,
    tier: 'MAIN',
    icon: <SiGithubactions size={24} color={SiGithubactionsHex} />,
  },
  {
    name: ETECH_STACK_LIST.FIGMA,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'USED',
    icon: <SiFigma size={24} color={SiFigmaHex} />,
  },
  {
    name: ETECH_STACK_LIST.POSTMAN,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiPostman size={24} color={SiPostmanHex} />,
  },
  {
    name: ETECH_STACK_LIST.GITHUB_COPILOT,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'MAIN',
    icon: <SiGithubcopilot size={24} color={SiGithubcopilotHex} />,
  },
  {
    name: ETECH_STACK_LIST.TWILIO,
    kind: ETECH_STACK_KIND.TOOL,
    tier: 'USED',
    icon: <CodeIcon />,
  },
];

type ITechStackCategory = {
  id: ETECH_STACK_KIND;
  label: string;
  name: string;
  description: string;
};

export const TECH_STACK_CATEGORY_CONSTANT: ITechStackCategory[] = [
  {
    id: ETECH_STACK_KIND.FRONTEND,
    label: 'FRONT',
    name: 'Frontend',
    description: '서비스의 첫인상을 만드는 화면을 구현합니다.',
  },
  {
    id: ETECH_STACK_KIND.BACKEND,
    label: 'BACK',
    name: 'Backend',
    description: '기능의 완성도를 높이는 서버를 설계합니다.',
  },
  {
    id: ETECH_STACK_KIND.LANGUAGE,
    label: 'LANG',
    name: 'Language',
    description: '문제를 해결하고 아이디어를 코드로 구현합니다.',
  },
  {
    id: ETECH_STACK_KIND.DATABASE,
    label: 'DB',
    name: 'Database',
    description: '서비스의 데이터를 안전하고 효율적으로 관리합니다.',
  },
  {
    id: ETECH_STACK_KIND.API,
    label: 'API',
    name: 'API',
    description: '화면과 서버를 자연스럽게 연결합니다.',
  },
  {
    id: ETECH_STACK_KIND.STATE,
    label: 'STATE',
    name: 'State',
    description: '복잡한 사용자 흐름을 예측 가능하게 관리합니다.',
  },
  {
    id: ETECH_STACK_KIND.ORM,
    label: 'ORM',
    name: 'ORM',
    description: '데이터를 다루는 코드를 간결하고 일관되게 유지합니다.',
  },
  {
    id: ETECH_STACK_KIND.STYLE,
    label: 'STYLE',
    name: 'Style',
    description: '사용하기 편한 인터페이스와 섬세한 움직임을 만듭니다.',
  },
  {
    id: ETECH_STACK_KIND.INFRA,
    label: 'INFRA',
    name: 'Infrastructure',
    description: '완성한 서비스가 안정적으로 운영되도록 준비합니다.',
  },
  {
    id: ETECH_STACK_KIND.CICD,
    label: 'CI/CD',
    name: 'CI / CD',
    description: '변경 사항을 빠르게 검증하고 안정적으로 배포합니다.',
  },
  {
    id: ETECH_STACK_KIND.TOOL,
    label: 'TOOL',
    name: 'Tools',
    description: '협업과 품질을 높여 개발의 밀도를 높입니다.',
  },
];
